print("Hello")
c=input("Where do you live?")
a=input("Your last name,first name?")
b=input("How old are you?")
print("Where do you live?",c)
print("Your last name,first name?",a)
print("How old are you?",b)
